"""add_invoice_tables

Revision ID: ebcb32fbb8da
Revises: 105a47620ede
Create Date: 2026-03-27 14:58:12.823380

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ebcb32fbb8da'
down_revision = '105a47620ede'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_item_id'), 'invoice_item', ['id'], unique=False)
    op.drop_index(op.f('ix_invoiceitem_id'), table_name='invoiceitem')
    op.drop_table('invoiceitem')
    op.alter_column('invoice', 'due_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoice', 'due_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_table('invoiceitem',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unit_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('discount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], name=op.f('invoiceitem_invoice_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('invoiceitem_pkey'))
    )
    op.create_index(op.f('ix_invoiceitem_id'), 'invoiceitem', ['id'], unique=False)
    op.drop_index(op.f('ix_invoice_item_id'), table_name='invoice_item')
    op.drop_table('invoice_item')
    # ### end Alembic commands ###